name: b_sims
description: Flutter project Port Information System.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  carousel_slider: ^4.0.0
  curved_navigation_bar: ^1.0.1
  google_fonts: ^2.2.0
  animations: ^2.0.2
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: '#1956B1'
  image: "assets/icon/logo.png"
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/